{% set version = "0.3.0" %}

context:
  version: "{{ version }}"

package:
  name: serial-monitor-rust
  version: "{{ version }}"

source:
  - url: https://github.com/hacknus/serial-monitor-rust/archive/refs/tags/v{{ version }}.tar.gz
    sha256: ed5382c75d97fd05c8bc95a8b17de12a023fabbe88d7794c05d8ef79ee3a1096

build:
  script: |
    
    if [[ $(uname) == "Darwin" ]]; then     
      cargo install cargo-bundle
      cargo bundle --release

    elif [[ $(uname) == "Linux" ]]; then     
      sudo apt-get update
      sudo apt-get install -y \
        libclang-dev libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev \
        libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libudev-dev
      cargo install cargo-bundle
      cargo bundle --release

    elif [[ $(uname) == "Windows" ]]; then
      cargo install cargo-wix
      cargo wix
    fi


requirements:
  host:
    - conda-forge::rust
  run:
    - conda-forge::rust

about:
  repository: https://github.com/hacknus/serial-monitor-rust
  license: GPL-3.0
  summary: A cross-platform serial monitor/plotter written entirely in rust.
extra:
  recipe-maintainers:
    - hacknus