context:
  version: "0.3.1"

package:
  name: serial-monitor-rust
  version: ${{ version }}

source:
  url: https://github.com/hacknus/serial-monitor-rust/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 3044e9a19c72efb240742f8a319f83b29efe3f9d2126dab9e3240e7609171079

build:
  # build numbers can be set arbitrarily
  number: 0
  script:
    # display the rust version
    - rustc --version
    - cargo --version
    - if: osx
      then:
        - export MACOSX_DEPLOYMENT_TARGET=10.15  # or the correct macOS version
        - export PATH="/usr/bin:$PATH"  # Ensure that system Clang is used, not a potentially conflicting version
        - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
        - cargo install --locked --bins --root ${PREFIX} --path .
    - if: linux
      then:
        - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
        - cargo install --locked --bins --root ${PREFIX} --path .
    - if: win
      then:
        - rustup update
        - rustc --version
        - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
        - cargo install --locked --bins --root ${PREFIX} --path . --verbose

requirements:
  host:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - pkg-config
    - if: linux
      then:
        - conda-forge::libclang
        - conda-forge::gtk3
        - conda-forge::libxcb
        - conda-forge::libxkbcommon
        - conda-forge::openssl
        - conda-forge::libudev
    - if: win
      then:
        rust

  run:
    - if: linux
      then:
        - conda-forge::libclang
        - conda-forge::gtk3
        - conda-forge::libxcb
        - conda-forge::libxkbcommon
        - conda-forge::openssl
        - conda-forge::libudev

about:
  repository: https://github.com/hacknus/serial-monitor-rust
  license: GPL-3.0
  summary: A cross-platform serial monitor/plotter written entirely in rust.
extra:
  recipe-maintainers:
    - hacknus
