context:
  version: "0.3.2"

package:
  name: serial-monitor-rust
  version: ${{ version }}

source:
  - url: https://github.com/hacknus/serial-monitor-rust/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 7d9e7f19f3dc86f74852dd0129dcb31feb08a3411269d337dba3463a4f479f01

build:
  number: 0
  script:
    # display the rust version
    - rustc --version
    - cargo --version
    - if: osx
      then:
        - export MACOSX_DEPLOYMENT_TARGET=10.15  # minimum os version
    - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
    - cargo install --locked --bins --root ${PREFIX} --path .

requirements:
  build:
    - if: win
      then:
        - rust=1.82  # required on windows explicitly, on macOS and linux the latest version is already installed

  host:
    - cargo-bundle-licenses
    - pkg-config
    - if: linux
      then:
        - ${{ compiler('rust') }}
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        # for egui, linux requires additional dependencies
        - conda-forge::libclang
        - conda-forge::gtk3
        - conda-forge::libxcb
        - conda-forge::libxkbcommon
        - conda-forge::openssl
        - conda-forge::libudev

  run:
    - if: linux
      then:
        # for egui, linux requires additional dependencies
        - conda-forge::libclang
        - conda-forge::gtk3
        - conda-forge::libxcb
        - conda-forge::libxkbcommon
        - conda-forge::openssl
        - conda-forge::libudev

tests:
  - package_contents:
      files:
        - if: unix
          then:
            bin/serial-monitor-rust
          else:
            bin/serial-monitor-rust.exe

about:
  repository: https://github.com/hacknus/serial-monitor-rust
  license: GPL-3.0
  summary: A cross-platform serial monitor/plotter written entirely in rust.
extra:
  recipe-maintainers:
    - hacknus
