context:
  version: "0.3.2"

package:
  name: serial-monitor-rust
  version: ${{ version }}

source:
  - url: https://github.com/hacknus/serial-monitor-rust/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 7d9e7f19f3dc86f74852dd0129dcb31feb08a3411269d337dba3463a4f479f01

build:
  - if: platform == "osx"
    then:
      script: |
        cargo install cargo-bundle
        cargo bundle --release
  - if: platform == "linux"
    then:
      script: |
        sudo apt-get update
        sudo apt-get install -y \
          libclang-dev libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev \
          libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libudev-dev
        cargo install cargo-bundle
        cargo bundle --release
  - if: platform == "win"
    then:
      script: |
        cargo install cargo-wix
        cargo wix

requirements:
  host:
    - rust
  run:
    - rust

about:
  repository: https://github.com/hacknus/serial-monitor-rust
  license: GPL-3.0
  summary: A cross-platform serial monitor/plotter written entirely in rust.
extra:
  recipe-maintainers:
    - hacknus
